// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicPlaylistOrganizer.Data;

#nullable disable

namespace MusicPlaylistOrganizer.Migrations
{
    [DbContext(typeof(MusicContext))]
    [Migration("20251122214331_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicPlaylistOrganizer.Models.Artist", b =>
                {
                    b.Property<int>("ArtistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistID"));

                    b.Property<string>("ApiSourceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtworkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtistID");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistID = 1,
                            Genre = "USA",
                            Name = "Lo-Fi Wizard"
                        },
                        new
                        {
                            ArtistID = 2,
                            Genre = "UK",
                            Name = "Neon Nights"
                        });
                });

            modelBuilder.Entity("MusicPlaylistOrganizer.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaylistID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlaylistID");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            PlaylistID = 1,
                            Description = "Lo-fi beats to focus.",
                            Name = "Chill Study Mix"
                        });
                });

            modelBuilder.Entity("MusicPlaylistOrganizer.Models.PlaylistTrack", b =>
                {
                    b.Property<int>("PlaylistID")
                        .HasColumnType("int");

                    b.Property<int>("TrackID")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("PlaylistID", "TrackID");

                    b.HasIndex("TrackID");

                    b.ToTable("PlaylistTracks");

                    b.HasData(
                        new
                        {
                            PlaylistID = 1,
                            TrackID = 1,
                            Position = 1
                        },
                        new
                        {
                            PlaylistID = 1,
                            TrackID = 2,
                            Position = 2
                        });
                });

            modelBuilder.Entity("MusicPlaylistOrganizer.Models.Track", b =>
                {
                    b.Property<int>("TrackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackID"));

                    b.Property<string>("ApiSourceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArtistID")
                        .HasColumnType("int");

                    b.Property<string>("ArtworkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrackID");

                    b.HasIndex("ArtistID");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            TrackID = 1,
                            ArtistID = 1,
                            DurationSeconds = 215,
                            Title = "Study Clouds"
                        },
                        new
                        {
                            TrackID = 2,
                            ArtistID = 2,
                            DurationSeconds = 198,
                            Title = "Midnight Neon"
                        });
                });

            modelBuilder.Entity("MusicPlaylistOrganizer.Models.PlaylistTrack", b =>
                {
                    b.HasOne("MusicPlaylistOrganizer.Models.Playlist", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicPlaylistOrganizer.Models.Track", "Track")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("TrackID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicPlaylistOrganizer.Models.Track", b =>
                {
                    b.HasOne("MusicPlaylistOrganizer.Models.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicPlaylistOrganizer.Models.Artist", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicPlaylistOrganizer.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("MusicPlaylistOrganizer.Models.Track", b =>
                {
                    b.Navigation("PlaylistTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
